# docker run -d -it --name mi-mongo --net mi-red -mount source=mi-volumen, target=/data/db mongo
services:
  mi-mongo:
    image: mongo
    container_name: mi-mongo # --name mi-daw-12
    stdin_open: true # -i
    tty: true # -t
    networks:
      mi-red: # --net mi-red
    volumes:
      - mi-volumen:/data/db # -mount source=mi-vol, target=/app/data

  mi-mongo-express:
    image: mongo-express
    container_name: mi-mongo-express # --name mi-daw-12
    stdin_open: true # -i
    tty: true # -t
    networks:
      mi-red: # --net mi-red
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo
    

networks:
  mi-red:
    ipam:
      driver: default # --driver bridge
      
volumes:
  mi-volumen:


