# docker run -d -it --name mi-mongo --net mi-red -mount source=mi-volumen, target=/data/db mongo
services:
  mi-mysql:
    image: mysql
    container_name: mi-mysql # --name mi-daw-12
    stdin_open: true # -i
    tty: true # -t
    networks:
      mi-mysql-red: # --net mi-red
        ipv4_address: 172.25.0.2 # --ip 172.100.0.10
    volumes:
      - mi-mysql-vol:/var/lib/mysql # -mount source=mi-vol, target=/app/data
    environment:
      - MYSQL_ROOT_PASSWORD=2daw

  mi-dashboard:
    image: phpmyadmin/phpmyadmin
    container_name: mi-dashboard # --name mi-daw-12
    stdin_open: true # -i
    tty: true # -t
    networks:
      mi-mysql-red: # --net mi-red
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=172.25.0.2
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=2daw
    
networks:
  mi-mysql-red:
    ipam:
      driver: default # --driver bridge
      config:
        - subnet: 172.25.0.0/16 # --subnet 172.100.0.0/16
      
volumes:
  mi-mysql-vol:


